package playerMenu;

public enum POSITION {
	PITCHER,
	FIRST_BASE_FIELDER,
	SECOND_BASE_FIELDER,
	THIRD_BASE_FIELDER,
	RIGHT_FIELDER,
	SHORTSTOP,
	LEFT_FIELDER,
	CENTER_FIELDER,
	DESIGNATED_HITTER,
	CATCHER
	
}
